[destination.postgres.credentials]

database = "hh_analytics_24_4"
username = "jugnuarora"
password = "analytics_coach" # replace with your password
host = "data-analytics-course-2.c8g8r1deus2v.eu-central-1.rds.amazonaws.com"
port = 5432
connect_timeout = 15